### ISSUE TITLE
How do I use this?

### ISSUE THREAD

**Issue by jonathanwall** [ajdnik/powerbar#1]
I've git cloned but I see an empty bar up top. How do I proceed further?

**Comment by ajdnik** [comment]
If you only see the bar without the left and right sides, it most likely means there is a problem with the `status-left.sh` and `status-right.sh` scripts. You can try and run them in the terminal and post the results here. The scripts are located in `$HOME/Library/Application\ Support/Übersicht/widgets/powerbar`.

I've also made some updates to the codebase to handle script errors, so if you pull the latest changes and refresh the widget you should see an error message if you're missing any of the binaries used to get the system info data. Lastly, I've also added console logging of the script outputs so you can see the outputs in Übersicht Menu > Show Debug Console.

**Comment by jonathanwall** [comment]
I apologize for not replying earlier. After your reply I recloned and it worked just fine. Thank you!
